name: main
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Tests
        run: dotnet test

      - name: Build Docker image
        run: docker-compose build
